"""initial domain schema

Revision ID: 29f9a58658d0
Revises:
Create Date: 2026-09-27 02:44:15.806059
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from spyke.infrastructure.database.base import GeoPoint, JsonValue

revision: str = "29f9a58658d0"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "league",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("code_ffvb", sa.String(length=32), nullable=False),
        sa.Column(
            "echelon",
            sa.Enum(
                "INTERNATIONAL",
                "NATIONAL",
                "REGIONAL",
                "DEPARTEMENTAL",
                name="echelon",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_league")),
        sa.UniqueConstraint("code_ffvb", name=op.f("uq_league_code_ffvb")),
    )
    op.create_table(
        "season",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_season")),
        sa.UniqueConstraint("start_date", "end_date", name="uq_season_dates"),
    )
    op.create_table(
        "venue",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("postal_code", sa.String(length=16), nullable=True),
        sa.Column("city", sa.String(length=255), nullable=True),
        sa.Column("coordinate", GeoPoint(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_venue")),
    )
    op.create_table(
        "club",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("code_ffvb", sa.BigInteger(), nullable=False),
        sa.Column("city", sa.String(length=255), nullable=True),
        sa.Column("department", sa.String(length=16), nullable=True),
        sa.Column("league_id", sa.Integer(), nullable=True),
        sa.Column("headquarters_address", sa.String(length=500), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("website", sa.String(length=500), nullable=True),
        sa.Column("phone_number", sa.String(length=32), nullable=True),
        sa.Column("colors", JsonValue(), nullable=False),
        sa.Column("coordinate", GeoPoint(), nullable=True),
        sa.ForeignKeyConstraint(
            ["league_id"], ["league.id"], name=op.f("fk_club_league_id_league")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_club")),
        sa.UniqueConstraint("code_ffvb", name=op.f("uq_club_code_ffvb")),
    )
    op.create_table(
        "competition",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("organizer_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("code_competition", sa.String(length=64), nullable=False),
        sa.Column(
            "gender",
            sa.Enum("MASCULIN", "FEMININ", "MIXTE", name="gender", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "category",
            sa.Enum(
                "SENIOR",
                "M21",
                "M18",
                "M15",
                "M13",
                "M11",
                "JEUNES",
                "VETERAN",
                name="category",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "echelon",
            sa.Enum(
                "INTERNATIONAL",
                "NATIONAL",
                "REGIONAL",
                "DEPARTEMENTAL",
                name="echelon",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "division",
            sa.Enum(
                "PRO_A",
                "PRO_B",
                "ELITE",
                "ELITE_AVENIR",
                "NATIONALE_1",
                "NATIONALE_2",
                "NATIONALE_3",
                "NATIONALE",
                "COUPE_DE_FRANCE",
                "COUPE_DE_FRANCE_BEACH",
                "COUPE_DE_FRANCE_ASSIS",
                "COUPE_DE_FRANCE_SOURD",
                "COUPE_DE_FRANCE_JEUNES",
                "PRE_NATIONALE",
                "REGIONALE_1",
                "REGIONALE",
                "REGIONALE_2",
                "REGIONALE_3",
                "REGIONALE_4",
                "JEUNES_ELITE",
                "JEUNES_REGIONALE",
                "PRE_REGIONALE",
                "DEPARTEMENTALE_1",
                "DEPARTEMENTALE",
                "DEPARTEMENTALE_2",
                "DEPARTEMENTALE_3",
                "DEPARTEMENTALE_4",
                "JEUNES_DEPARTEMENTALE",
                "LOISIR",
                "UNKNOW",
                name="division",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organizer_id"], ["league.id"], name=op.f("fk_competition_organizer_id_league")
        ),
        sa.ForeignKeyConstraint(
            ["season_id"], ["season.id"], name=op.f("fk_competition_season_id_season")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competition")),
        sa.UniqueConstraint("season_id", "code_competition", name="uq_competition_season_code"),
    )
    op.create_table(
        "team_season",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("competition_id", sa.Integer(), nullable=False),
        sa.Column("club_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["club_id"], ["club.id"], name=op.f("fk_team_season_club_id_club")),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competition.id"],
            name=op.f("fk_team_season_competition_id_competition"),
        ),
        sa.ForeignKeyConstraint(
            ["season_id"], ["season.id"], name=op.f("fk_team_season_season_id_season")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team_season")),
        sa.UniqueConstraint("season_id", "competition_id", "name", name="uq_team_season_name"),
    )
    op.create_table(
        "match",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("competition_id", sa.Integer(), nullable=False),
        sa.Column("venue_id", sa.Integer(), nullable=True),
        sa.Column("home_team_id", sa.Integer(), nullable=False),
        sa.Column("away_team_id", sa.Integer(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "SCHEDULED",
                "PLAYED",
                "POSTPONED",
                "CANCELLED",
                "FORFEIT",
                "DOUBLE_FORFEIT",
                "UNKNOWN",
                name="matchstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("home_sets", sa.Integer(), nullable=True),
        sa.Column("away_sets", sa.Integer(), nullable=True),
        sa.Column("remarks", sa.String(length=2000), nullable=True),
        sa.ForeignKeyConstraint(
            ["away_team_id"], ["team_season.id"], name=op.f("fk_match_away_team_id_team_season")
        ),
        sa.ForeignKeyConstraint(
            ["competition_id"], ["competition.id"], name=op.f("fk_match_competition_id_competition")
        ),
        sa.ForeignKeyConstraint(
            ["home_team_id"], ["team_season.id"], name=op.f("fk_match_home_team_id_team_season")
        ),
        sa.ForeignKeyConstraint(
            ["season_id"], ["season.id"], name=op.f("fk_match_season_id_season")
        ),
        sa.ForeignKeyConstraint(["venue_id"], ["venue.id"], name=op.f("fk_match_venue_id_venue")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match")),
        sa.UniqueConstraint("code", name=op.f("uq_match_code")),
    )
    op.create_table(
        "match_set",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("home_score", sa.Integer(), nullable=False),
        sa.Column("away_score", sa.Integer(), nullable=False),
        sa.Column("serving_side", sa.Enum("A", "B", name="side", native_enum=False), nullable=True),
        sa.ForeignKeyConstraint(
            ["match_id"], ["match.id"], name=op.f("fk_match_set_match_id_match"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match_set")),
        sa.UniqueConstraint("match_id", "number", name="uq_match_set_number"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("match_set")
    op.drop_table("match")
    op.drop_table("team_season")
    op.drop_table("competition")
    op.drop_table("club")
    op.drop_table("venue")
    op.drop_table("season")
    op.drop_table("league")
    # ### end Alembic commands ###
