"""add entity resolution decisions

Revision ID: bbd360bb9bd3
Revises: a45eb3487481
Create Date: 2026-09-27 21:43:45.824719
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "bbd360bb9bd3"
down_revision: str | Sequence[str] | None = "a45eb3487481"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entity_resolution",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_system", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("normalized_name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("canonical_entity_id", sa.Integer(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("source_document_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["source_document.id"],
            name=op.f("fk_entity_resolution_source_document_id_source_document"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entity_resolution")),
        sa.UniqueConstraint(
            "source_system",
            "entity_type",
            "external_id",
            name=("uq_entity_resolution_external_reference"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("entity_resolution")
    # ### end Alembic commands ###
